// import { Inter } from "next/font/google";
import { Noto_Naskh_Arabic } from "next/font/google";
import "./globals.css";
import Nav from "./ui/Nav";
import Footer from "./ui/Footer";

// const inter = Inter({ subsets: ["latin"] });
const inter = Noto_Naskh_Arabic({ subsets: ["arabic"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
